### ISSUE TITLE
$check->requestRun() not working

### ISSUE THREAD

**Issue by pfischer-22c** [ohdearapp/ohdear-php-sdk#12]
When retrieving all checks from a site and requesting a run nothing happens:
```
foreach($site->checks as $check){
  $check->requestRun();
}
```

It seems that the method body of `requestRun()` in class Check is empty.

I guess it should be something like:
```
public function requestRun()
{
  $updatedCheck = $this->ohDear->requestRun($this->id);

  $this->enabled = $updatedCheck->enabled;
}

```

**Comment by mattiasgeniar** [comment]
Hi @pfischer-22c ! Just found the bug indeed, a new release was tagged. Lost sight of this issue, sorry it took so long!

**Comment by pfischer-22c** [comment]
Hi Mattias,

thx dir the reply. Do you have any news for me regarding my other request
to extend the API capabilities by setting the site properties?

Kind regards,
Philipp


Mattias Geniar <notifications@github.com> schrieb am Sa., 2. Mai 2020,
08:59:

**Comment by mattiasgeniar** [comment]
On the roadmap, but that one takes a bit more to flesh out - I'll keep you posted via our support ticket :-)
