### ISSUE TITLE
Get status page  error

### ISSUE THREAD

**Issue by ybert** [ohdearapp/ohdear-php-sdk#39]
When I try to get a specific status page like this : 
```php
        $this->ohDear->statusPage(config('ohdear.status_page_id'));
```

I get this error : Cannot assign null to property OhDear\\PhpSdk\\Resources\\StatusPage::$domain of type string

In fact the StatusPage model has a string property $domain that can't be null.
Can you make it nullable as the API can return null in this value. Maybe it is the case for other attributes ?

**Comment by freekmurze** [comment]
This has been fixed in the latest release.
