### ISSUE TITLE
Creation of dynamic property OhDear\PhpSdk\Resources\Site::$... is deprecated

### ISSUE THREAD

**Issue by tobimori** [ohdearapp/ohdear-php-sdk#42]
Missing:
- `$label`
- `$teamId`
- `$groupName`
- `$tags`
- `$notes`
- `$latestRunDate`
- `$summarizedCheckResult`
- `$usesHttps`

(and probably more, in all of the other classes too.)

**Comment by freekmurze** [comment]
I'd accept a PR that adds these properties

**Comment by tobimori** [comment]
a bit hard without a definition to do as this is basically typing everything by trial and error ^^
