### ISSUE TITLE
Exception for uptime check when no data is there as site is too new

### ISSUE THREAD

**Issue by tobimori** [ohdearapp/ohdear-php-sdk#43]
```OhDear\PhpSdk\OhDear::transformCollection(): Argument #1 ($collection) must be of type array, string given, called in `/vendor/ohdearapp/ohdear-php-sdk/src/Actions/ManagesUptime.php` on line 16```

```php
		$uptime = $ohdear->site($id)->uptime(
			date('Ymdhis', strtotime("-1 year")),
			date('Ymdhis'),
			'day'
		);
```

**Comment by freekmurze** [comment]
Could you try making this change in `ManagesUptime`? Does that fix the problem?

```
        return $this->transformCollection(
            $this->get("sites/$siteId/uptime?filter[started_at]={$startedAt}&filter[ended_at]={$endedAt}&split={$split}") ?? [],
            Uptime::class
        );
```

**Comment by tobimori** [comment]
probably not, `$this->get()` returns `"[]"`. just as a string.

what's interesting is that it works fine with other types when no entry is there like broken links

**Comment by freekmurze** [comment]
This has been fixed in the latest version.
