### ISSUE TITLE
Validation Exception - The description must be a string.

### ISSUE THREAD

**Issue by keithbrink** [ohdearapp/ohdear-php-sdk#46]
I am using the laravel schedule monitor with the --keep-old method to push my cron jobs for monitoring to Oh Dear, however, there seems to be a validation issue where the description is not being validated as a string even though an empty string is passed. You can see that the description param is set to an empty string here: 

https://github.com/spatie/laravel-schedule-monitor/blob/682df2ecd3a4085740dffce984f8c1b1892c2a0d/src/Commands/SyncCommand.php#L157

But I still receive a validation error from Oh Dear: 

https://jasara-tech.sentry.io/share/issue/4ec55a7a053949d783f4e9e5b29cc433/

Not sure if this is a package issue or server issue, so let me know if this should be brought up somewhere else.

**Comment by freekmurze** [comment]
Hi, this problem was fixed on Oh Dear's side. Could you try again?
